ekf_filter_node:
  ros__parameters:
  # config/config.yaml
    use_sim_time: true
    frequency: 30.0  # Run the filter at 30 Hz
    sensor_timeout: 0.1  # Allow 100 ms for data to arrive
    two_d_mode: true  # Use 2D mode (assume the robot operates on a flat surface)

    # World Frame
    world_frame: "odom"  # The global frame of reference
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"  # The frame tied to the robot

    # State Vector
    publish_tf: true  # Publish transforms for visualization
    publish_acceleration: true

    # # Process noise covariance (tune these values as needed)
    # process_noise_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

    # Wheel Odometry Settings
    odom0: smart_car/wheel/odom
    odom0_config: [true, true, true,
                       false, false, false,
                       true,  true,  true,
                       false, false, true,
                       false, false, false]
    odom0_queue_size: 10



    # IMU Settings
    imu0: imu_dataa
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false,  false,  false,
                  true,  true,  true]
    imu0_queue_size: 10
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 7
    imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
    imu0_twist_rejection_threshold: 0.8                #
    imu0_linear_acceleration_rejection_threshold: 0.8  #

    # # Initial estimation covariance
    # initial_estimate_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
