# config/nav2_params.yaml

amcl:
  ros__parameters:
    use_sim_time: false
    map_frame: "map"
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    update_min_d: 0.2
    update_min_a: 0.1
    transform_tolerance: 0.5
    # ... other AMCL parameters as needed ...

# Global Costmap configuration
global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 1.0
      publish_frequency: 1.0
      resolution: 0.05
      robot_radius: 0.2
      inflation_layer:
        inflation_radius: 0.5
      # ... other global costmap parameters ...

# Local Costmap configuration
local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: "odom"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      robot_radius: 0.2
      inflation_layer:
        inflation_radius: 0.5
      # ... other local costmap parameters ...

# Planner Server configuration
planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      # ... other planner parameters ...

# Controller Server configuration
controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_vel_x: 0.0
    min_vel_theta: 0.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.1
      max_vel_x: 0.26
      min_vel_theta: 0.1
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      # ... other controller parameters ...

# Behavior Tree configuration
bt_navigator:
  ros__parameters:
    plugin_lib_names: ["nav2_tree/BtActionNode", "nav2_tree/BtServiceNode", "nav2_tree/BtConditionNode"]
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
